var datasource = [
  {'name': 'HTML5', 'fullname': 'HTML5 will be the new standard for HTML.'},
  {'name': 'CSS3', 'fullname': 'CSS3 is the latest standard for CSS.'},
  {'name': 'Javascript','fullname': 'JavaScript is the scripting language of the Web.'},
  {'name': 'Ajax', 'fullname': 'AJAX = Asynchronous JavaScript and XML.'},
  {'name': 'jQuery', 'fullname': 'jQuery greatly simplifies JavaScript programming'},
  {'name': 'jQuery UI', 'fullname': 'Query UI is a curated set of user interface interactions, effects, widgets, and themes.'},
  {'name': 'Bootstrap', 'fullname': 'Sleek, intuitive, and powerful mobile first front-end framework'},
  {'name': 'Backbone.js', 'fullname': 'Backbone.js gives structure to web applications by providing models, collections, views and routers.'},
  {'name': 'underscore.js', 'fullname': 'Underscore is a utility-belt library for JavaScript.'},
  {'name': 'Jade', 'fullname': ' Jade is designed primarily for server side templating in node.js.'},
  {'name': 'Angular.js', 'fullname': 'AngularJS is what HTML would have been, had it been designed for building web-apps'},
  {'name': 'Socket.io', 'fullname': 'Socket.IO aims to make realtime apps possible in every browser and mobile device.'},
  {'name': 'Node.js', 'fullname': 'Node.js enables us to run thousands of user applications.'},
  {'name': 'Express.js', 'fullname': 'Express is a minimal and flexible node.js web application framework.'},
  {'name': 'mongoose', 'fullname': 'Elegant MongoDB object modeling for Node.js'},
  {'name': 'SVG', 'fullname': 'This is an XML namespace, first defined in the Scalable Vector Graphics.'},
  {'name': 'Canvas', 'fullname': 'The canvas tag is used to draw graphics, on the fly, on a web page.'},
  {'name': 'WebGL', 'fullname': 'WebGL is a cross-platform, royalty-free web standard for a low-level 3D graphics API'},
  {'name': 'JSHint', 'fullname': 'JSHint is a tool that helps to detect errors and potential problems in your JavaScript code.'},
  {'name': 'Chrome DevTools', 'fullname': 'DevToos are a set web authoring and debugging tools built into Google Chrome'},
  {'name': 'Jasmine', 'fullname': 'DOM-less simple JavaScript testing framework.'},
  {'name': 'Mocha', 'fullname': 'the fun, simple, flexible JavaScript test framework'},
  {'name': 'Grunt', 'fullname': 'The JavaScript Task Runner.'},
  {'name': 'Bower', 'fullname': 'Bower is a package manager for the web.'},
  {'name': 'Yeoman', 'fullname': 'Yeoman is more than just a tool. It\'s a workflow.'}
];