var datasource = [
  {"banner": "HTML5", "content": "HTML5 will be the new standard for HTML."},
  {"banner": "CSS3", "content": "CSS3 is the latest standard for CSS."},
  {"banner": "Javascript","content": "JavaScript is the scripting language of the Web."},
  {"banner": "Ajax", "content": "AJAX = Asynchronous JavaScript and XML."},
  {"banner": "jQuery", "content": "jQuery greatly simplifies JavaScript programming"},
  {"banner": "jQuery UI", "content": "Query UI is a curated set of user interface interactions, effects, widgets, and themes."},
  {"banner": "Bootstrap", "content": "Sleek, intuitive, and powerful mobile first front-end framework"},
  {"banner": "Backbone.js", "content": "Backbone.js gives structure to web applications by providing models, collections, views and routers."},
  {"banner": "underscore.js", "content": "Underscore is a utility-belt library for JavaScript."},
  {"banner": "Jade", "content": " Jade is designed primarily for server side templating in node.js."},
  {"banner": "Angular.js", "content": "AngularJS is what HTML would have been, had it been designed for building web-apps"},
  {"banner": "Socket.io", "content": "Socket.IO aims to make realtime apps possible in every browser and mobile device."},
  {"banner": "Node.js", "content": "Node.js enables us to run thousands of user applications."},
  {"banner": "Express.js", "content": "Express is a minimal and flexible node.js web application framework."},
  {"banner": "mongoose", "content": "Elegant MongoDB object modeling for Node.js"},
  {"banner": "SVG", "content": "This is an XML namespace, first defined in the Scalable Vector Graphics."},
  {"banner": "Canvas", "content": "The canvas tag is used to draw graphics, on the fly, on a web page."},
  {"banner": "WebGL", "content": "WebGL is a cross-platform, royalty-free web standard for a low-level 3D graphics API"},
  {"banner": "JSHint", "content": "JSHint is a tool that helps to detect errors and potential problems in your JavaScript code."},
  {"banner": "Chrome DevTools", "content": "DevToos are a set web authoring and debugging tools built into Google Chrome"},
  {"banner": "Jasmine", "content": "DOM-less simple JavaScript testing framework."},
  {"banner": "Mocha", "content": "the fun, simple, flexible JavaScript test framework"},
  {"banner": "Grunt", "content": "The JavaScript Task Runner."},
  {"banner": "Bower", "content": "Bower is a package manager for the web."},
  {"banner": "Yeoman", "content": "Yeoman is more than just a tool. It's a workflow."}
];